# resolve-type-names: false

class ::User < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::User, ::User::ActiveRecord_Relation, ::Integer]

  module ::User::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def given_name: () -> ::String

    def given_name=: (::String) -> ::String

    def given_name?: () -> bool

    def given_name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def given_name_change: () -> [ ::String?, ::String? ]

    def given_name_will_change!: () -> void

    def given_name_was: () -> ::String?

    def given_name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def given_name_previous_change: () -> ::Array[::String?]?

    def given_name_previously_was: () -> ::String?

    def given_name_before_last_save: () -> ::String?

    def given_name_change_to_be_saved: () -> ::Array[::String?]?

    def given_name_in_database: () -> ::String?

    def saved_change_to_given_name: () -> ::Array[::String?]?

    def saved_change_to_given_name?: () -> bool

    def will_save_change_to_given_name?: () -> bool

    def restore_given_name!: () -> void

    def clear_given_name_change: () -> void

    def given_name_before_type_cast: () -> ::String

    def given_name_for_database: () -> ::String

    def family_name: () -> ::String

    def family_name=: (::String) -> ::String

    def family_name?: () -> bool

    def family_name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def family_name_change: () -> [ ::String?, ::String? ]

    def family_name_will_change!: () -> void

    def family_name_was: () -> ::String?

    def family_name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def family_name_previous_change: () -> ::Array[::String?]?

    def family_name_previously_was: () -> ::String?

    def family_name_before_last_save: () -> ::String?

    def family_name_change_to_be_saved: () -> ::Array[::String?]?

    def family_name_in_database: () -> ::String?

    def saved_change_to_family_name: () -> ::Array[::String?]?

    def saved_change_to_family_name?: () -> bool

    def will_save_change_to_family_name?: () -> bool

    def restore_family_name!: () -> void

    def clear_family_name_change: () -> void

    def family_name_before_type_cast: () -> ::String

    def family_name_for_database: () -> ::String

    def email: () -> ::String

    def email=: (::String) -> ::String

    def email?: () -> bool

    def email_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def email_change: () -> [ ::String?, ::String? ]

    def email_will_change!: () -> void

    def email_was: () -> ::String?

    def email_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def email_previous_change: () -> ::Array[::String?]?

    def email_previously_was: () -> ::String?

    def email_before_last_save: () -> ::String?

    def email_change_to_be_saved: () -> ::Array[::String?]?

    def email_in_database: () -> ::String?

    def saved_change_to_email: () -> ::Array[::String?]?

    def saved_change_to_email?: () -> bool

    def will_save_change_to_email?: () -> bool

    def restore_email!: () -> void

    def clear_email_change: () -> void

    def email_before_type_cast: () -> ::String

    def email_for_database: () -> ::String
  end
  include ::User::GeneratedAttributeMethods
  module ::User::GeneratedAliasAttributeMethods
    include ::User::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::User::GeneratedAliasAttributeMethods
  def subscriptions: () -> ::Subscription::ActiveRecord_Associations_CollectionProxy
  def subscriptions=: (::Subscription::ActiveRecord_Associations_CollectionProxy | ::Array[::Subscription]) -> (::Subscription::ActiveRecord_Associations_CollectionProxy | ::Array[::Subscription])
  def subscription_ids: () -> ::Array[::Integer]
  def subscription_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def transactions: () -> ::Transaction::ActiveRecord_Associations_CollectionProxy
  def transactions=: (::Transaction::ActiveRecord_Associations_CollectionProxy | ::Array[::Transaction]) -> (::Transaction::ActiveRecord_Associations_CollectionProxy | ::Array[::Transaction])
  def transaction_ids: () -> ::Array[::Integer]
  def transaction_ids=: (::Array[::Integer]) -> ::Array[::Integer]

  module ::User::GeneratedAssociationMethods
  end
  include ::User::GeneratedAssociationMethods

  module ::User::GeneratedRelationMethods
  end

  class ::User::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::User]
    include ::User::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::User, ::Integer]
  end

  class ::User::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::User]
    include ::User::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::User, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::User
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::User]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::User
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::User]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::User
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::User]
    def reload: () -> ::Array[::User]

    def replace: (::Array[::User]) -> void
    def delete: (*::User | ::Integer) -> ::Array[::User]
    def destroy: (*::User | ::Integer) -> ::Array[::User]
    def <<: (*::User | ::Array[::User]) -> self
    def prepend: (*::User | ::Array[::User]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Subscription < ::ApplicationRecord
end
class ::Subscription::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Transaction < ::ApplicationRecord
end
class ::Transaction::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
