# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rswag-ui` gem.
# Please instead update this file by running `bin/tapioca gem rswag-ui`.


# pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:4
module Rswag; end

# pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:5
module Rswag::Ui
  class << self
    # pkg:gem/rswag-ui#lib/rswag/ui.rb:10
    def config; end

    # @yield [config]
    #
    # pkg:gem/rswag-ui#lib/rswag/ui.rb:6
    def configure; end

    # pkg:gem/rswag-ui#lib/rswag/ui.rb:14
    def deprecator; end

    # pkg:gem/rswag-ui#lib/rswag/ui/engine.rb:7
    def railtie_helpers_paths; end

    # pkg:gem/rswag-ui#lib/rswag/ui/engine.rb:7
    def railtie_namespace; end

    # pkg:gem/rswag-ui#lib/rswag/ui/engine.rb:7
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/rswag-ui#lib/rswag/ui/engine.rb:7
    def table_name_prefix; end

    # pkg:gem/rswag-ui#lib/rswag/ui/engine.rb:7
    def use_relative_model_naming?; end
  end
end

# Extend Rack HTTP Basic Authentication, as per RFC 2617.
#
# @api private
#
# pkg:gem/rswag-ui#lib/rswag/ui/basic_auth.rb:10
class Rswag::Ui::BasicAuth < ::Rack::Auth::Basic
  # @api private
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/basic_auth.rb:11
  def call(env); end

  private

  # @api private
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/basic_auth.rb:26
  def base_path(url); end

  # @api private
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/basic_auth.rb:19
  def env_matching_path(env); end
end

# pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:6
class Rswag::Ui::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:13
  def initialize; end

  # Returns the value of attribute assets_root.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:11
  def assets_root; end

  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:38
  def basic_auth_credentials(username, password); end

  # Returns the value of attribute basic_auth_enabled.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:8
  def basic_auth_enabled; end

  # Sets the attribute basic_auth_enabled
  #
  # @param value the value to set the attribute basic_auth_enabled to.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:8
  def basic_auth_enabled=(_arg0); end

  # Returns the value of attribute config_object.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:9
  def config_object; end

  # Sets the attribute config_object
  #
  # @param value the value to set the attribute config_object to.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:9
  def config_object=(_arg0); end

  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:43
  def get_binding; end

  # Returns the value of attribute oauth_config_object.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:10
  def oauth_config_object; end

  # Sets the attribute oauth_config_object
  #
  # @param value the value to set the attribute oauth_config_object to.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:10
  def oauth_config_object=(_arg0); end

  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:33
  def openapi_endpoint(url, name); end

  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:28
  def swagger_endpoint(url, name); end

  # Returns the value of attribute template_locations.
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/configuration.rb:7
  def template_locations; end
end

# pkg:gem/rswag-ui#lib/rswag/ui/engine.rb:6
class Rswag::Ui::Engine < ::Rails::Engine; end

# pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:3
class Rswag::Ui::Middleware < ::Rack::Static
  # @return [Middleware] a new instance of Middleware
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:5
  def initialize(app, config); end

  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:10
  def call(env); end

  private

  # @return [Boolean]
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:25
  def base_path?(env); end

  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:43
  def csp; end

  # @return [Boolean]
  #
  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:29
  def index_path?(env); end

  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:33
  def render_template; end

  # pkg:gem/rswag-ui#lib/rswag/ui/middleware.rb:39
  def template_filename; end
end
