---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    Bearer:
      description: Response token from the login
      type: apiKey
      name: Authorization
      in: header
paths:
  "/v1/register":
    post:
      summary: Creates a blog
      tags:
      - Register
      parameters: []
      responses:
        '201':
          description: user registered
          content:
            application/json:
              examples:
                success:
                  value:
                    user:
                      created_at: '2026-04-04T02:18:40.116Z'
                      email: test@example.com
                      family_name: example family name
                      given_name: example given name
                      id: 1
                      roles: []
        '422':
          description: user exists
          content:
            application/json:
              examples:
                success:
                  value:
                    error:
                    - Email has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                given_name:
                  type: string
                family_name:
                  type: string
              required:
              - email
              - password
              - given_name
              - family_name
            examples:
              Register a user:
                summary: A request example
                value:
                  email: test@example.com
                  password: '0123456789'
                  given_name: example given name
                  family_name: example family name
  "/v1/login":
    post:
      summary: Logs in a user
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: Login succeeded
          content:
            application/json:
              examples:
                success:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxfSwiZXhwIjoxNzc1Mjg2MjEwfQ.e1HbNox2aIGH8aqPIBAYPbwAiAX_Xck-ju9la95KwNg
                    user:
                      created_at: '2026-04-04T02:18:40.116Z'
                      email: test@example.com
                      family_name: example family name
                      given_name: example given name
                      id: 1
                      roles: []
        '401':
          description: Login failed
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Unauthorized
                  summary: '#<RSpec::Core::Example "returns a 401 response">'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                given_name:
                  type: string
                family_name:
                  type: string
              required:
              - email
              - password
            examples:
              Login a user:
                summary: Returns the user's information and an authorization token.
                  It should be passed as the bairer token to other authorized requests.
                value:
                  email: test@example.com
                  password: '0123456789'
  "/v1/products":
    get:
      summary: Get available products
      tags:
      - Product
      security:
      - Bearer: {}
      responses:
        '200':
          description: Returns all products
          content:
            application/json:
              examples:
                success:
                  value:
                    products:
                    - id: 1
                      name: com.samansa.subscription.monthly
                      created_at: '2026-04-04T12:39:23.954Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
  "/v1/subscriptions":
    get:
      summary: Get all subscriptions for the user
      tags:
      - Subscriptions
      security:
      - Bearer: {}
      responses:
        '200':
          description: Returns all subscriptions for the user
          content:
            application/json:
              examples:
                success:
                  value:
                    subscriptions: []
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
    post:
      summary: Create a subscription for the user
      tags:
      - Subscription
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: Subscription created
          content:
            application/json:
              examples:
                success:
                  value:
                    subscription:
                      id: 1
                      user_id: 1
                      product_id: 1
                      created_at: '2026-04-04T12:53:09.007Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
        '422':
          description: Creation failed
          content:
            application/json:
              examples:
                success:
                  value:
                    errors:
                      product:
                      - must exist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
              required:
              - product_id
            examples:
              Create a subscription:
                summary: A request example
                value:
                  product_id: 1
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
