---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    Bearer:
      description: Response token from the login
      type: apiKey
      name: Authorization
      in: header
paths:
  "/v1/webhooks/apple/transactions":
    post:
      summary: Create a transaction for a subscription
      tags:
      - Webhooks
      security:
      - Bearer: {}
      description: "\nAn endpoint used for adding transactions to a subscription.
        Transactions record actions by the user for a subscription. The last \ntransaction
        is the active one for a subscription, while the rest can be used for record
        keeping.\n\nThere are three different action types: `purchase`, `cancel` and
        `renew`.\n\nNOTE: The `transaction_id` of this request maps to the related
        subscription `id` and `notification_uuid` is recorded as the `external_id`.\n\n-
        A purchase transaction is the first transaction for a subscription.  It is
        not active until created.\n- A renew must have a `purchase_date` that starts
        at the expiration of the previous transaction.  \n- A cancel transaction must
        share the same `purchase_date` and `expiration_date` as the previous transaction.\n
        \       "
      parameters: []
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              examples:
                success:
                  value:
                    transaction:
                      id: 1
                      external_id: 4d249252-118d-42c6-99b8-75ded060ceea
                      source: apple
                      action: purchase
                      amount: '3.9'
                      currency: USD
                      purchase_date: '1990-01-01T00:01:00.000Z'
                      expires_date: '1990-02-01T12:00:00.000Z'
                      created_at: '2026-04-04T13:21:00.691Z'
                      subscription_id: 1
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
        '422':
          description: Creation failed
          content:
            application/json:
              examples:
                success:
                  value:
                    errors:
                      product:
                      - must exist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
              required:
              - product_id
            examples:
              Purchase a subscription:
                summary: Purchase a subscription.
                value:
                  transaction:
                    notification_uuid: 4d249252-118d-42c6-99b8-75ded060ceea
                    type: purchase
                    amount: '3.9'
                    currency: USD
                    transaction_id: 1
                    product_id: 1
                    purchase_date: '1990-01-01T00:01:00.000Z'
                    expires_date: '1990-02-01T12:00:00.000Z'
              Cancel a subscription:
                summary: Cancel a subscription.
                value:
                  transaction:
                    notification_uuid: f949aaaa-f912-463d-8721-56da71e86a4d
                    type: cancel
                    transaction_id: 1
                    product_id: 1
                    purchase_date: '1990-01-01T00:01:00.000Z'
                    expires_date: '1990-02-01T12:00:00.000Z'
              Renew a subscription:
                summary: Renew a subscription.
                value:
                  transaction:
                    notification_uuid: f949aaaa-f912-463d-8721-56da71e86a4d
                    type: renew
                    amount: '3.9'
                    currency: USD
                    transaction_id: 1
                    product_id: 1
                    purchase_date: '1990-01-01T00:01:00.000Z'
                    expires_date: '1990-02-01T12:00:00.000Z'
  "/v1/register":
    post:
      summary: Creates a blog
      tags:
      - Authorization
      description: "\nRegisters a new user in the system. You can then use the login
        endpoint to get an api token.\n\nThis is a simple login mecanism that uses
        email as the unique idenifier.\n      "
      parameters: []
      responses:
        '201':
          description: user registered
          content:
            application/json:
              examples:
                success:
                  value:
                    user:
                      created_at: '2026-04-04T02:18:40.116Z'
                      email: test@example.com
                      family_name: example family name
                      given_name: example given name
                      id: 1
                      roles: []
        '422':
          description: user exists
          content:
            application/json:
              examples:
                success:
                  value:
                    error:
                    - Email has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                given_name:
                  type: string
                family_name:
                  type: string
              required:
              - email
              - password
              - given_name
              - family_name
            examples:
              Register a user:
                summary: A request example
                value:
                  email: test@example.com
                  password: '0123456789'
                  given_name: example given name
                  family_name: example family name
  "/v1/login":
    post:
      summary: Logs in a user
      tags:
      - Authorization
      description: "\nAuthenticate a user using a username and password to recieve
        a token.  It should be passed to the HEAD of api requests in the format of
        `{ Authorization: \"Bearer :token\" }`.\n      "
      parameters: []
      responses:
        '200':
          description: Login succeeded
          content:
            application/json:
              examples:
                success:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxfSwiZXhwIjoxNzc1Mjg2MjEwfQ.e1HbNox2aIGH8aqPIBAYPbwAiAX_Xck-ju9la95KwNg
                    user:
                      created_at: '2026-04-04T02:18:40.116Z'
                      email: test@example.com
                      family_name: example family name
                      given_name: example given name
                      id: 1
                      roles: []
        '401':
          description: Login failed
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Unauthorized
                  summary: '#<RSpec::Core::Example "returns a 401 response">'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                given_name:
                  type: string
                family_name:
                  type: string
              required:
              - email
              - password
            examples:
              Login a user:
                summary: Logs in a user
                value:
                  email: test@example.com
                  password: '0123456789'
  "/v1/products":
    get:
      summary: Get available products
      tags:
      - Products
      security:
      - Bearer: {}
      parameters:
      - name: limit
        in: query
        schema:
          type: number
      - name: offset
        in: query
        schema:
          type: number
      description: "\nA type representing products that can be subscribed to.\n      "
      responses:
        '200':
          description: Returns all products
          content:
            application/json:
              examples:
                success:
                  value:
                    products:
                    - id: 1
                      name: com.samansa.subscription.monthly
                      created_at: '2026-04-04T12:39:23.954Z'
                    count: 1
                    limit: 20
                    offset: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
  "/v1/subscriptions/{id}":
    get:
      summary: Retrieves a subscription
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Subscriptions
      security:
      - Bearer: {}
      description: "\nReturns a detail view of a subscription, including the last_transaction
        which represents the current subscription state.\n\nA subscription is not
        active until it as a purchase or renew transaction.\n      "
      responses:
        '200':
          description: Returns the user's subscription detail
          content:
            application/json:
              examples:
                success:
                  value:
                    subscription:
                      id: 1
                      user_id: 1
                      product_id: 1
                      created_at: '2026-04-04T12:53:09.007Z'
                      last_transaction:
                        id: 1
                        action: purchase
                        created_at: '2026-04-04T13:21:00.691Z'
                        currency: USD
                        expires_date: '1990-02-01T12:00:00.000Z'
                        external_id: 4d249252-118d-42c6-99b8-75ded060ceea
                        purchase_date: '1990-01-01T00:01:00.000Z'
                        source: apple
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Not Found
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
  "/v1/subscriptions":
    get:
      summary: Get all subscriptions for the user
      tags:
      - Subscriptions
      security:
      - Bearer: {}
      parameters:
      - name: limit
        in: query
        schema:
          type: number
      - name: offset
        in: query
        schema:
          type: number
      description: "\nReturns a list of the current user subscriptions.\n      "
      responses:
        '200':
          description: Returns all subscriptions for the user
          content:
            application/json:
              examples:
                success:
                  value:
                    subscriptions:
                    - id: 1
                      user_id: 1
                      product_id: 1
                      created_at: '2026-04-04T12:53:09.007Z'
                    count: 1
                    limit: 20
                    offset: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
    post:
      summary: Create a subscription for the user
      tags:
      - Subscriptions
      security:
      - Bearer: {}
      parameters: []
      responses:
        '201':
          description: Subscription created
          content:
            application/json:
              examples:
                success:
                  value:
                    subscription:
                      id: 1
                      user_id: 1
                      product_id: 1
                      created_at: '2026-04-04T12:53:09.007Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                success:
                  value:
                    message: Please log in
        '422':
          description: Creation failed
          content:
            application/json:
              examples:
                success:
                  value:
                    errors:
                      product:
                      - must exist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
              required:
              - product_id
            examples:
              Create a subscription:
                summary: A request example
                value:
                  product_id: 1
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
