---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/register":
    post:
      summary: Creates a blog
      tags:
      - Register
      parameters: []
      responses:
        '201':
          description: user registered
          content:
            application/json:
              examples:
                success:
                  value:
                    user:
                      created_at: '2026-04-04T02:18:40.116Z'
                      email: test@example.com
                      family_name: example family name
                      given_name: example given name
                      id: 1
                      roles: []
        '422':
          description: user exists
          content:
            application/json:
              examples:
                success:
                  value:
                    error:
                    - Email has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                given_name:
                  type: string
                family_name:
                  type: string
              required:
              - email
              - password
              - given_name
              - family_name
            examples:
              Register a user:
                summary: A request example
                value:
                  email: test@example.com
                  password: '0123456789'
                  given_name: example given name
                  family_name: example family name
  "/v1/login":
    post:
      summary: Logs in a user
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: login succeeded
          content:
            application/json:
              examples:
                success:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxfSwiZXhwIjoxNzc1Mjg2MjEwfQ.e1HbNox2aIGH8aqPIBAYPbwAiAX_Xck-ju9la95KwNg
                    user:
                      created_at: '2026-04-04T02:18:40.116Z'
                      email: test@example.com
                      family_name: example family name
                      given_name: example given name
                      id: 1
                      roles: []
        '422':
          description: login failed
          content:
            application/json:
              examples:
                success:
                  value:
                    error:
                    - Email has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                given_name:
                  type: string
                family_name:
                  type: string
              required:
              - email
              - password
            examples:
              Login a user:
                summary: Returns the user's information and an authorization token.
                  It should be passed as the bairer token to other authorized requests.
                value:
                  email: test@example.com
                  password: '0123456789'
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
